### ISSUE TITLE
Add the profile picture

### ISSUE THREAD

**Issue by Tharindu37** [Tharindu37/testhost#8]
- Add the profile picture like this.
![Screenshot 2023-01-14 182520](https://user-images.githubusercontent.com/88996660/212473494-eba39f60-868d-4a72-a030-3a2789a9e3c6.jpg)

**Additional context**
profile picture
![IMG_7614](https://user-images.githubusercontent.com/88996660/212473550-8e382ac6-3488-4bf0-bcd9-6210284ba26a.jpeg)

**Are you working on it?**
No

**Comment by TLHPHEMAPALA** [comment]
I wanna work with your project.I can do this.

**Comment by Tharindu37** [comment]
@hiruhemapala Sure
